name: garmin-sync-garmin

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 15 * * *'
env:
  GITHUB_NAME: njzyshare
  GITHUB_EMAIL: feimummy@126.com
  ## 佳明中国区配置（源账号）
  GARMIN_AUTH_DOMAIN: ${{ secrets.GARMIN_AUTH_DOMAIN }}
  GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}

  ## 佳明国际区配置（目标账号）
  GARMIN_INTL_EMAIL: ${{ secrets.GARMIN_INTL_EMAIL }}
  GARMIN_INTL_PASSWORD: ${{ secrets.GARMIN_INTL_PASSWORD }}
  GARMIN_INTL_AUTH_DOMAIN: ${{ secrets.GARMIN_INTL_AUTH_DOMAIN }}

  ## 通用配置
  GARMIN_NEWEST_NUM: ${{ secrets.GARMIN_NEWEST_NUM }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set Variables
        id: set_variables
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Garmin Cross-Region Sync
        run: |
          python scripts/garmin/garmin_sync_garmin.py
      - name: Push new cookie
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'feat(sync): cross-region garmin sync' || echo "nothing to commit"
          git push || echo "nothing to push"
